
#enum materialProperty ioOpacity ioIridescence ioAnisotropy ioClearCoat ioIOR ioClearCoatGloss ioVolume ioMicroprotrusionsGloss ioRefractionBlur ioSpecularEdgePower ioSubSurface ioFlatSpecular ioRefractionChromatic ioAmbientOcclusion ioMask ioMicroprotrusions ioMetalness ioRefraction ioRefractionMetalness ioGloss ioRoughness ioSheen  ioDisplacement

out float OutValue;
OutValue = materialProperty;

