from typing import Any
from enum import Enum
class vec2:
	x: Any
	y: Any
	def __init__(self): ...
	def __init__(self, S = Any): ...
	def __init__(self, X = Any, Y = Any): ...
	def Copy (self, Src = Any): ...
	def SetZero (self): ...
	def SetOne (self): ...
	def Set (self, S = Any): ...
	def Set (self, X = Any, Y = Any): ...
	def Transform (self, _0 = Any): ...
	def TransformCoordinate (self, _0 = Any): ...
	def TransformNormal (self, _0 = Any): ...
	def Equals (self, _0 = Any, _1 = Any, Eps = Any): ...
	def Length (self): ...
	def LengthSq (self): ...
	def Normalize (self): ...
	def NormalizeSafe (self, Fallback = Any): ...
	def IsValid (self): ...
	def IsNormalized (self, Eps = Any): ...
	def IsZero (self, Eps = Any): ...
	def Round (self, _0 = Any): ...
	def ToRound (self): ...
	def Abs (self, _0 = Any): ...
	def Fract (self, _0 = Any): ...
	def Angle (self, _0 = Any, _1 = Any): ...
	def AreaSigned (self, t0 = Any, t1 = Any, t2 = Any): ...
	def Ccw (self, _0 = Any, _1 = Any): ...
	def Clamp (self, Value = Any, Lo = Any, Hi = Any): ...
	def Distance (self, _0 = Any, _1 = Any): ...
	def DistanceSq (self, _0 = Any, _1 = Any): ...
	def Dot (self, _0 = Any, _1 = Any): ...
	def Lerp (self, _0 = Any, _1 = Any, _2 = Any): ...
	def Lerp05 (self, _0 = Any, _1 = Any): ...
	def Max (self, _0 = Any, _1 = Any): ...
	def Min (self, _0 = Any, _1 = Any): ...
	def PerpCw (self, _0 = Any): ...
	def PerpCcw (self, _0 = Any): ...
	def Reflect (self, RayDir = Any, Normal = Any): ...
	def Refract (self, RayDir = Any, Normal = Any, Eta = Any): ...
	def Truncate (self, u = Any, MaxLength = Any): ...
	def RandRange1 (self): ...
	def RandNormal (self): ...
	def Rand (self, Lo = Any, Hi = Any): ...
	def distance2 (self, _0 = Any): ...
	def distance (self, _0 = Any): ...
	def DistanceToLineSegSq (self, A = Any, B = Any, pScale = Any): ...
	def SegIntersection (self, L0 = Any, L1 = Any, R0 = Any, R1 = Any, l = Any, r = Any): ...
	def FromBaryCentric (self, t0 = Any, t1 = Any, t2 = Any, u = Any, v = Any): ...
	def FromPolar (self, Radius = Any, Angle = Any): ...
	Zero: Any
	One: Any
	Infinity: Any
	AxisX: Any
	AxisY: Any
	AxisNegX: Any
	AxisNegY: Any
	def GetDimension (self): ...
	def ToFloatPtr (self): ...
	def ToFloatPtr (self): ...
	def ToPolar (self, Radius = Any, Angle = Any): ...
	def ToBaryCentric (self, t0 = Any, t1 = Any, t2 = Any, u = Any, v = Any): ...
	def IsInsideTri (self, t0 = Any, t1 = Any, t2 = Any): ...
	def ToString (self, Prec = Any): ...
	def ToNormal (self): ...
	def ToPerpCw (self): ...
	def ToPerpCcw (self): ...
	def Clear (self): ...
	def AddWithWeight (self, src = Any, weight = float): ...
	def SetPosition (self, aX = float, aY = float): ...
	def GetPosition (self): ...
class vec3:
	x: Any
	y: Any
	z: Any
	def __init__(self): ...
	def __init__(self, S = Any): ...
	def __init__(self, X = Any, Y = Any, Z = Any): ...
	def __init__(self, XY = Any, Z = Any): ...
	def __init__(self, v = Any): ...
	def Copy (self, Src = Any): ...
	def SetZero (self): ...
	def SetOne (self): ...
	def SetRandRange1 (self): ...
	def Set (self, S = Any): ...
	def Set (self, X = Any, Y = Any, Z = Any): ...
	def Set (self, XY = Any, Z = Any): ...
	def TransformCoordinate (self, _0 = Any): ...
	def TransformNormal (self, _0 = Any): ...
	def TransformNormalTransposed (self, _0 = Any): ...
	def Transform (self, _0 = Any): ...
	def Rotate (self, _0 = Any): ...
	def Rotate (self, _0 = Any): ...
	def distance (self, u = Any): ...
	def distanceSq (self, u = Any): ...
	def dot (self, u = Any): ...
	def cross (self, u = Any, v = Any): ...
	def Clear (self): ...
	def AddWithWeight (self, src = Any, weight = float): ...
	def SetPosition (self, aX = float, aY = float, aZ = float): ...
	def GetPosition (self): ...
	def Equals (self, _0 = Any, _1 = Any, Eps = Any): ...
	def Length (self): ...
	def Length2 (self): ...
	def LengthSq (self): ...
	def LengthM (self): ...
	def Normalize (self): ...
	def Normalize2 (self): ...
	def NormalizeSafe (self, Fallback = Any): ...
	def FixDegenerateNormal (self): ...
	def FixDenormals (self): ...
	def IsValid (self): ...
	def IsNormalized (self, Eps = float): ...
	def IsZero (self, Eps = float): ...
	def Round (self): ...
	def Abs (self, _0 = Any): ...
	def Angle (self, _0 = Any, _1 = Any): ...
	def Angle (self, p1 = Any, p2 = Any, p3 = Any, normal = Any): ...
	def AreaSigned (self, t0 = Any, t1 = Any, t2 = Any): ...
	def BaryCentric (self, t0 = Any, t1 = Any, t2 = Any, f = Any, g = Any): ...
	def Clamp (self, _0 = Any, _1 = Any, _2 = Any): ...
	def Cross (self, _0 = Any, _1 = Any): ...
	def SetCross (self, _0 = Any, _1 = Any): ...
	def Distance (self, _0 = Any, _1 = Any): ...
	def Distance2 (self, _0 = Any, _1 = Any): ...
	def DistanceSq (self, _0 = Any, _1 = Any): ...
	def Dot (self, _0 = Any, _1 = Any): ...
	def Lerp (self, _0 = Any, _1 = Any, _2 = Any): ...
	def Lerp05 (self, _0 = Any, _1 = Any): ...
	def Max (self, _0 = Any, _1 = Any): ...
	def Min (self, _0 = Any, _1 = Any): ...
	def Reflect (self, RayDir = Any, Normal = Any): ...
	def Refract (self, RayDir = Any, Normal = Any, Eta = Any): ...
	def Slerp (self, n0 = Any, n1 = Any, s = Any): ...
	def Truncate (self, u = Any, MaxLen = Any): ...
	def RandRange1 (self): ...
	def RandNormal (self): ...
	def Rand (self, Lo = Any, Hi = Any): ...
	def Project (self, v1 = Any, v2 = Any): ...
	def Perpendicular (self, v1 = Any): ...
	def TriProjectionSolidAngle (self, a = Any, b = Any, c = Any): ...
	Zero: Any
	One: Any
	Infinity: Any
	AxisX: Any
	AxisY: Any
	AxisZ: Any
	AxisNegX: Any
	AxisNegY: Any
	AxisNegZ: Any
	def GetDimension (self): ...
	def ToFloatPtr (self): ...
	def ToFloatPtr (self): ...
	def ToVec2 (self): ...
	def ToVec2 (self): ...
	def ToString (self, Prec = Any): ...
	def ToAngles (self): ...
	def GetOrthonormal (self): ...
	def GetOrthonormalPair (self): ...
	def MakeOrthonormalTo (self, vec = Any): ...
	def ToPolarXZ (self, Radius = Any, Angle = Any): ...
	def FromPolarXZ (self, Radius = Any, Angle = Any): ...
	def ToBaryCentric (self, t0 = Any, t1 = Any, t2 = Any, f = Any, g = Any): ...
	def ToNormal (self): ...
	def ToPerps (self, X = Any, Y = Any): ...
	def ToPerp (self): ...
	def RayTri (self, RayOrig = Any, RayDir = Any, t0 = Any, t1 = Any, t2 = Any, u = Any, v = Any, t = Any, BackFaceCull = Any): ...
	def PointInTriangle (self, p = Any, t0 = Any, t1 = Any, t2 = Any): ...
class vec4:
	x: Any
	y: Any
	z: Any
	w: Any
	def __init__(self): ...
	def __init__(self, S = Any): ...
	def __init__(self, X = Any, Y = Any, Z = Any, W = Any): ...
	def __init__(self, XY = Any, Z = Any, W = Any): ...
	def __init__(self, XY = Any, ZW = Any): ...
	def __init__(self, XYZ = Any, W = Any): ...
	def SetZero (self): ...
	def Set (self, S = Any): ...
	def Set (self, X = Any, Y = Any, Z = Any, W = Any): ...
	def Set (self, XY = Any, Z = Any, W = Any): ...
	def Set (self, XY = Any, ZW = Any): ...
	def Set (self, XYZ = Any, W = Any): ...
	def Copy (self, pSrc = Any): ...
	def Transform (self, _0 = Any): ...
	def Equals (self, _0 = Any, _1 = Any, Eps = Any): ...
	def Length (self): ...
	def LengthSq (self): ...
	def Normalize (self): ...
	def NormalizeSafe (self, Fallback = Any): ...
	def IsNormalized (self, Eps = Any): ...
	def IsZero (self, Eps = Any): ...
	def Abs (self, _0 = Any): ...
	def Dot (self, _0 = Any, _1 = Any): ...
	def Lerp (self, _0 = Any, _1 = Any, _2 = Any): ...
	def Max (self, _0 = Any, _1 = Any): ...
	def Min (self, _0 = Any, _1 = Any): ...
	Zero: Any
	One: Any
	Infinity: Any
	AxisX: Any
	AxisY: Any
	AxisZ: Any
	AxisW: Any
	AxisNegX: Any
	AxisNegY: Any
	AxisNegZ: Any
	AxisNegW: Any
	def ToFloatPtr (self): ...
	def ToFloatPtr (self): ...
	def ToVec2 (self): ...
	def ToVec2 (self): ...
	def ToVec3 (self): ...
	def ToVec3 (self): ...
	def GetDimension (self): ...
	def ToString (self, Prec = Any): ...
	def Clear (self): ...
	def AddWithWeight (self, src = Any, weight = float): ...
	def SetPosition (self, aX = float, aY = float, aZ = float, aW = float): ...
	def GetPosition (self): ...
class mat3:
	def __init__(self): ...
	def __init__(self, _00 = Any, _01 = Any, _02 = Any, _10 = Any, _11 = Any, _12 = Any, _20 = Any, _21 = Any, _22 = Any): ...
	def Copy (self, Float9 = Any): ...
	def CopyTransposed (self, Float9 = Any): ...
	def SetZero (self): ...
	def SetIdentity (self): ...
	def GetRow (self, Index = Any): ...
	def GetRow0 (self): ...
	def GetRow1 (self): ...
	def GetRow2 (self): ...
	def Row (self, Index = Any): ...
	def Row0 (self): ...
	def Row1 (self): ...
	def Row2 (self): ...
	def SetRow (self, Index = Any, _1 = Any): ...
	def SetRow0 (self, _0 = Any): ...
	def SetRow1 (self, _0 = Any): ...
	def SetRow2 (self, _0 = Any): ...
	def SetRow (self, Index = Any, X = Any, Y = Any, Z = Any): ...
	def SetRow0 (self, X = Any, Y = Any, Z = Any): ...
	def SetRow1 (self, X = Any, Y = Any, Z = Any): ...
	def SetRow2 (self, X = Any, Y = Any, Z = Any): ...
	def GetCol (self, Index = Any): ...
	def GetCol0 (self): ...
	def GetCol1 (self): ...
	def GetCol2 (self): ...
	def SetCol (self, Index = Any, _1 = Any): ...
	def SetCol0 (self, _0 = Any): ...
	def SetCol1 (self, _0 = Any): ...
	def SetCol2 (self, _0 = Any): ...
	def SetCol (self, Index = Any, X = Any, Y = Any, Z = Any): ...
	def SetCol0 (self, X = Any, Y = Any, Z = Any): ...
	def SetCol1 (self, X = Any, Y = Any, Z = Any): ...
	def SetCol2 (self, X = Any, Y = Any, Z = Any): ...
	def SetElem (self, Row = int, Col = int, Value = float): ...
	def GetElem (self, Row = Any, Col = Any): ...
	def Elem (self, Row = Any, Col = Any): ...
	def Trace (self): ...
	def Determinant (self): ...
	def Equals (self, _0 = Any, _1 = Any, Eps = Any): ...
	def IsZero (self, Eps = Any): ...
	def IsIdentity (self, Eps = Any): ...
	def IsSymmetric (self, Eps = Any): ...
	def IsOrthonormal (self, Eps = Any): ...
	def Add (self, R = Any): ...
	def Sub (self, R = Any): ...
	def Mul (self, R = Any): ...
	def Mul (self, s = Any): ...
	Zero: Any
	Identity: Any
	def Transpose (self, _0 = Any): ...
	def Invert (self, Fm = Any, To = Any): ...
	def OrthoNormalize (self, Src = Any): ...
	def Rotation (self, Axis = Any, Angle = Any): ...
	def RotationX (self, Angle = Any): ...
	def RotationY (self, Angle = Any): ...
	def RotationZ (self, Angle = Any): ...
	def RotationXYZ (self, Pitch = Any, Yaw = Any, Roll = Any): ...
	def EulerZYX (self, eulerX = Any, eulerY = Any, eulerZ = Any): ...
	def Scaling (self, XYZ = Any): ...
	def Scaling (self, X = Any, Y = Any): ...
	def Scaling (self, X = Any, Y = Any, Z = Any): ...
	def Scaling (self, XY = Any): ...
	def Scaling (self, XYZ = Any): ...
	def ToFloatPtr (self): ...
	def ToFloatPtr (self): ...
	def ToMat4 (self): ...
	def ToQuat (self): ...
	def ToVectors (self, Forward = Any, Right = Any, Up = Any): ...
	def FromVectors (self, Forward = Any, Right = Any, Up = Any): ...
	def FromForward (self, Forward = Any): ...
	def ToForward (self): ...
	def ToRight (self): ...
	def ToUp (self): ...
	def ToAngles (self): ...
class mat4:
	def __init__(self): ...
	def __init__(self, Rotation = Any, Translation = Any): ...
	def __init__(self, Scaling = Any, Translation = Any): ...
	def __init__(self, _00 = Any, _01 = Any, _02 = Any, _03 = Any, _10 = Any, _11 = Any, _12 = Any, _13 = Any, _20 = Any, _21 = Any, _22 = Any, _23 = Any, _30 = Any, _31 = Any, _32 = Any, _33 = Any): ...
	def Copy (self, Float16 = Any): ...
	def CopyTransposed (self, Float16 = Any): ...
	def SetZero (self): ...
	def SetIdentity (self): ...
	def GetRow (self, Index = Any): ...
	def GetRow0 (self): ...
	def GetRow1 (self): ...
	def GetRow2 (self): ...
	def GetRow3 (self): ...
	def Row (self, Index = Any): ...
	def Row0 (self): ...
	def Row1 (self): ...
	def Row2 (self): ...
	def Row3 (self): ...
	def SetRow (self, Index = Any, _1 = Any): ...
	def SetRow0 (self, _0 = Any): ...
	def SetRow1 (self, _0 = Any): ...
	def SetRow2 (self, _0 = Any): ...
	def SetRow3 (self, _0 = Any): ...
	def SetRow (self, Index = Any, X = Any, Y = Any, Z = Any, W = Any): ...
	def SetRow0 (self, X = Any, Y = Any, Z = Any, W = Any): ...
	def SetRow1 (self, X = Any, Y = Any, Z = Any, W = Any): ...
	def SetRow2 (self, X = Any, Y = Any, Z = Any, W = Any): ...
	def SetRow3 (self, X = Any, Y = Any, Z = Any, W = Any): ...
	def GetCol (self, Index = Any): ...
	def GetCol0 (self): ...
	def GetCol1 (self): ...
	def GetCol2 (self): ...
	def GetCol3 (self): ...
	def SetCol (self, Index = Any, _1 = Any): ...
	def SetCol0 (self, _0 = Any): ...
	def SetCol1 (self, _0 = Any): ...
	def SetCol2 (self, _0 = Any): ...
	def SetCol3 (self, _0 = Any): ...
	def SetCol (self, Index = Any, X = Any, Y = Any, Z = Any, W = Any): ...
	def SetCol0 (self, X = Any, Y = Any, Z = Any, W = Any): ...
	def SetCol1 (self, X = Any, Y = Any, Z = Any, W = Any): ...
	def SetCol2 (self, X = Any, Y = Any, Z = Any, W = Any): ...
	def SetCol3 (self, X = Any, Y = Any, Z = Any, W = Any): ...
	def SetElem (self, Row = int, Col = int, Value = float): ...
	def GetElem (self, Row = Any, Col = Any): ...
	def Elem (self, Row = Any, Col = Any): ...
	def Trace (self): ...
	def Determinant (self): ...
	def Equals (self, _0 = Any, _1 = Any, Eps = Any): ...
	def IsZero (self, Eps = float): ...
	def IsIdentity (self, Eps = float): ...
	def IsSymmetric (self, Eps = float): ...
	def IsOrthonormal (self, Eps = float): ...
	def Add (self, R = Any): ...
	def Sub (self, R = Any): ...
	def Mul (self, R = Any): ...
	def Mul (self, s = Any): ...
	def ToFloatPtr (self): ...
	def ToFloatPtr (self): ...
	def ToString (self, Prec = Any): ...
	def ToMat3 (self): ...
	def ToNormalMatrix (self): ...
	def ToQuat (self): ...
	def GetTranslation (self): ...
	def SetTranslation (self, _0 = Any): ...
	def GetScaling (self): ...
	def SetScaling (self, _0 = Any): ...
	def GetRotation (self): ...
	def SetRotation (self, _0 = Any): ...
	def Transpose (self, _0 = Any): ...
	def Invert (self, Fm = Any, To = Any): ...
	Zero: Any
	Identity: Any
	def Translation (self, X = Any, Y = Any): ...
	def Translation (self, X = Any, Y = Any, Z = Any): ...
	def Translation (self, XY = Any): ...
	def Translation (self, XYZ = Any): ...
	def Rotation (self, Axis = Any, Angle = Any): ...
	def RotationX (self, Angle = Any): ...
	def RotationY (self, Angle = Any): ...
	def RotationZ (self, Angle = Any): ...
	def RotationXYZ (self, Pitch = Any, Yaw = Any, Roll = Any): ...
	def EulerZYX (self, eulerX = Any, eulerY = Any, eulerZ = Any): ...
	def RotationAt (self, Orig = Any, Angle = Any): ...
	def RotationAt (self, Orig = Any, Axis = Any, Angle = Any): ...
	def Scaling (self, XYZ = Any): ...
	def Scaling (self, X = Any, Y = Any): ...
	def Scaling (self, X = Any, Y = Any, Z = Any): ...
	def Scaling (self, XY = Any): ...
	def Scaling (self, XYZ = Any): ...
	def ScalingAt (self, OrigX = Any, OrigY = Any, ScaleXY = Any): ...
	def ScalingAt (self, OrigX = Any, OrigY = Any, ScaleX = Any, ScaleY = Any): ...
	def ScalingAt (self, Orig = Any, ScaleXY = Any): ...
	def ScalingAt (self, Orig = Any, ScaleX = Any, ScaleY = Any): ...
	def ScalingAt (self, Orig = Any, Scale = Any): ...
	def ScalingAt (self, Orig = Any, ScaleXYZ = Any): ...
	def ScalingAt (self, Orig = Any, ScaleX = Any, ScaleY = Any, ScaleZ = Any): ...
	def ScalingAt (self, Orig = Any, Scale = Any): ...
	def ScalingAt (self, Orig = Any, Dir = Any, Scale = float): ...
	def Perspective (self, YFov = float, AspectWtoH = float, Znear = float, Zfar = float): ...
	def PerspectiveInf (self, YFov = Any, AspectWtoH = Any, Znear = Any): ...
	def Ortho (self, Width = Any, Height = Any, Znear = Any, Zfar = Any): ...
	def Ortho (self, Left = Any, Right = Any, Bottom = Any, Top = Any, Znear = Any, Zfar = Any): ...
	def Ortho (self, B = Any): ...
	def CubeViewProjection (self, Pos = Any, Side = Any, Radius = Any, GL = Any): ...
	def LookAtViewProjection (self, LookFrom = Any, LookAt = Any, FovY = Any, AspectYtoH = Any, Znear = Any, Zfar = Any): ...
class cBounds:
	def __init__(self): ...
	def __init__(self, p = Any): ...
	def __init__(self, bMin = Any, bMax = Any): ...
	def __init__(self): ...
	def GetMin (self): ...
	def GetMax (self): ...
	def GetMin (self): ...
	def GetMax (self): ...
	def Set (self, Min = Any, Max = Any): ...
	def SetMin (self, _0 = Any): ...
	def SetMax (self, _0 = Any): ...
	def GetSize (self): ...
	def GetSizeX (self): ...
	def GetSizeY (self): ...
	def GetSizeZ (self): ...
	def GetDiagonal (self): ...
	def GetCenter (self): ...
	def GetLargestAxis (self): ...
	def SetEmpty (self): ...
	def SetZero (self): ...
	def IsEmpty (self): ...
	Empty: Any
	Zero: Any
	One: Any
	def AddPoint (self, _0 = Any): ...
	def AddBounds (self, _0 = Any): ...
	def Inflate (self, DeltaX = Any, DeltaY = Any, DeltaZ = Any): ...
	def Inflate (self, DeltaXYZ = Any): ...
	def Inflate (self, Delta = Any): ...
	def Translate (self, _0 = Any): ...
	def Translate (self, _0 = Any): ...
	def DistanceToPointSq (self, p = Any): ...
	def DistanceToPointSq (self, p = Any): ...
	def ContainsPoint (self, _0 = Any): ...
	def ContainsCircle (self, Center = Any, Radius = Any): ...
	def ContainsPoint (self, _0 = Any): ...
	def ContainsBounds (self, _0 = Any): ...
	def IntersectsBounds (self, _0 = Any): ...
	def RayIntersection (self, RayOrig = Any, RayDir = Any, Scale = Any): ...
	def RayIntersection (self, RayOrig = Any, RayDir = Any, Cross = Any): ...
	def LineIntersection (self, RayOrig = Any, RayDir = Any, Scale = Any): ...
	def FromPoints (self, pPoints = Any, nCount = Any): ...
	def FromPoints (self, pPoints = Any, nCount = Any): ...
	def FromPoints (self, Points = Any): ...
	def ToPoints (self, P8 = Any): ...
	def ToSphere (self): ...
	def Lerp (self, l = Any, r = Any, s = Any): ...
	def Transform (self, B = Any, T = Any): ...
	def ToRect (self): ...
class cRotation:
	def __init__(self): ...
	def __init__(self, Orig = Any, Axis = Any, Angle = Any): ...
	def Set (self, Orig = Any, Axis = Any, Angle = Any): ...
	def GetOrig (self): ...
	def GetAxis (self): ...
	def GetAngle (self): ...
	def SetOrig (self, Orig = Any): ...
	def SetAxis (self, Axis = Any): ...
	def SetAngle (self, Angle = Any): ...
	def ReCalcMatrix (self): ...
	def Normalize180 (self): ...
	def Normalize360 (self): ...
	def ToAngles (self): ...
	def ToQuat (self): ...
	def ToMat3 (self): ...
	def ToMat4 (self): ...
	def ToAngularVelocity (self): ...
class cQuat:
	x: Any
	y: Any
	z: Any
	w: Any
	def __init__(self): ...
	def __init__(self, X = Any, Y = Any, Z = Any, W = Any): ...
	def SetIdentity (self): ...
	def SetZero (self): ...
	def IsZero (self, Eps = float): ...
	def Set (self, X = Any, Y = Any, Z = Any, W = Any): ...
	def Set (self, XYZ = Any, W = Any): ...
	def Mul (self, _0 = Any, _1 = Any): ...
	def Div (self, _0 = Any, _1 = Any): ...
	def Equals (self, _0 = Any, _1 = Any, Eps = Any): ...
	def EqualRotations (self, _0 = Any, _1 = Any, Eps = Any): ...
	def SameHemisphere (self, _0 = Any, _1 = Any): ...
	def Compress (self): ...
	def CalcW (self): ...
	def Length (self): ...
	def LengthSq (self): ...
	def Normalize (self): ...
	def IsNormalized (self, Eps = Any): ...
	def Conjugate (self, _0 = Any): ...
	def Dot (self, _0 = Any, _1 = Any): ...
	def Exp (self, _0 = Any): ...
	def Invert (self, _0 = Any): ...
	def Lerp (self, q0 = Any, q1 = Any, s = Any, ShortestPath = Any): ...
	def Ln (self, _0 = Any): ...
	def LnDif (self, _0 = Any, _1 = Any): ...
	def Slerp (self, q0 = Any, q1 = Any, s = Any, ShortestPath = Any): ...
	def Squad (self, q1 = Any, A = Any, B = Any, C = Any, s = Any): ...
	def SquadSetup (self, q0 = Any, q1 = Any, q2 = Any, q3 = Any, A = Any, B = Any, C = Any): ...
	Identity: Any
	Zero: Any
	def GetDimension (self): ...
	def ToAngles (self): ...
	def ToRotation (self): ...
	def ToMat3 (self): ...
	def ToMat4 (self): ...
	def ToAngularVelocity (self): ...
	def ToFloatPtr (self): ...
	def ToFloatPtr (self): ...
	def ToStr (self, nPrec = Any): ...
class cPlane:
	d: Any
	def __init__(self): ...
	def __init__(self, A = Any, B = Any, C = Any, D = Any): ...
	def __init__(self, t0 = Any, t1 = Any, t2 = Any): ...
	def __init__(self, Pt = Any, Normal = Any): ...
	def __init__(self, Normal = Any, Offset = Any): ...
	def SetNormalize (self, A = Any, B = Any, C = Any, D = Any): ...
	def GetNormal (self): ...
	def SetNormal (self, _0 = Any): ...
	def SetOffset (self, Offset = Any): ...
	def GetOffset (self): ...
	def MutableNormal (self): ...
	def SetFromPoints (self, t0 = Any, t1 = Any, t2 = Any): ...
	def SetFromPointAndNormal (self, Pt = Any, Normal = Any): ...
	def MoveToPoint (self, p = Any): ...
	def Distance (self, p = Any): ...
	def ProjectPoint (self, p = Any): ...
	def ProjectVector (self, u = Any): ...
	def MirrorPoint (self, p = Any): ...
	def MirrorVector (self, u = Any): ...
	def MirrorOrient (self, q = Any): ...
	def FlipNormal (self): ...
	def BelowPlane (self, B = Any, T = Any): ...
	def ClassifyPoint (self, p = Any, Eps = Any): ...
	def ClassifySphere (self, S = Any, Eps = Any): ...
	def IsFrontFacingTo (self, Dir = Any): ...
	def RayIntersection (self, RayOrig = Any, RayDir = Any, pScale = Any, pCross = Any): ...
	def SegIntersection (self, S0 = Any, S1 = Any, pCross = Any): ...
	def PlaneIntersection (self, P = Any, pCross = Any, pDir = Any): ...
	def ToPtr (self): ...
	def ToPtr (self): ...
	def ToVec4 (self): ...
	def ToVec4 (self): ...
	def FitToPoints (self, points = Any): ...
class BoolOpType(Enum):
	BOOL_MERGE = ...
	BOOL_ADD = ...
	BOOL_SUBTRACT = ...
	BOOL_INTERSECT = ...
class Mesh:
	def __init__(self): ...
	def __init__(self): ...
	def __init__(self, m = Any): ...
	def Read (self, name = str): ...
	def Write (self, name = str): ...
	def valid (self): ...
	def geometry (self): ...
	def clear (self): ...
	def addTransformed (self, m = Any, t = Any): ...
	def boolean (self, m = Any, op = Any): ...
	def transform (self, transform = Any): ...
class Image:
	def Read (self, name = str): ...
	def Write (self, name = str): ...
class symm:
	def enable (self, _enable = Any): ...
	def enabled (self): ...
	def disable (self): ...
	def xyz (self, x = Any, y = Any, z = Any): ...
	def is_xyz (self): ...
	def x (self): ...
	def y (self): ...
	def z (self): ...
	def axial (self, n = int, extraMirror = Any, stepSymmetry = Any): ...
	def is_axial (self): ...
	def axialOrder (self): ...
	def extraMirror (self): ...
	def stepSymmetry (self): ...
	def axialMirror (self, n = int, extraMirror = Any, stepSymmetry = Any): ...
	def isAxialMirror (self): ...
	def translation (self, numX = int, stepX = float, numY = int, stepY = float, numZ = int, stepZ = float): ...
	def is_translation (self): ...
	def numX (self): ...
	def stepX (self): ...
	def numY (self): ...
	def stepY (self): ...
	def numZ (self): ...
	def stepZ (self): ...
	def toGlobalSpace (self): ...
	def toLocalSpace (self): ...
	def toGeneral (self): ...
	def set_start (self, pos = Any): ...
	def start (self): ...
	def set_end (self, pos = Any): ...
	def end (self): ...
	def showSymmetryPlane (self, show = Any): ...
	def setCustomSymetryTransforms (self, symmetryTransforms = Any): ...
	def isCustomSymmetry (self): ...
	def getCurrentTransforms (self): ...
	def getCurrentPlanes (self): ...
class SceneElement:
	def __init__(self): ...
	def __init__(self, vo = Any): ...
	def __init__(self, c = Any): ...
	def __init__(self): ...
	def parent (self): ...
	def childCount (self): ...
	def child (self, index = int): ...
	def isSculptObject (self): ...
	def isCurve (self): ...
	def setTransform (self, Transform = Any): ...
	def transform (self, Transform = Any): ...
	def density (self, density_value = float): ...
	def transform_single (self, Transform = Any): ...
	def getTransform (self): ...
	def clear (self): ...
	def name (self): ...
	def rename (self, name = str): ...
	def addChild (self, name = str): ...
	def findInSubtree (self, name = str): ...
	def mergeSubtree (self, booleanMerge = Any): ...
	def mergeTo (self, dest = Any, op = Any): ...
	def copyMergeTo (self, dest = Any, op = Any): ...
	def removeSubtree (self): ...
	def removeSubtreeItem (self, index = int): ...
	def remove (self): ...
	def duplicate (self): ...
	def duplicateAsInstance (self): ...
	def changeParent (self, newParent = Any): ...
	def visible (self): ...
	def Volume (self): ...
	def select (self): ...
	def selectOne (self): ...
	def unselectAll (self): ...
	def selected (self): ...
	def collectSelected (self): ...
class Volume:
	def __init__(self): ...
	def __init__(self, tb = Any): ...
	def __init__(self, vo = Any): ...
	def valid (self): ...
	def isSurface (self): ...
	def isVoxelized (self): ...
	def toSurface (self): ...
	def toVoxels (self): ...
	def enableVoxelsColoring (self, enable = Any): ...
	def color (self, CL = Any): ...
	def color (self, r = float, g = float, b = float, a = float): ...
	def color (self, r = float, g = float, b = float): ...
	def color (self, colorid = str): ...
	def gloss (self, value = float): ...
	def roughness (self, value = float): ...
	def metal (self, value = float): ...
	def mergeMesh (self, mesh = Any, transform = Any, op = Any): ...
	def mergeMeshWithTexture (self, mesh = Any, transform = Any, op = Any): ...
	def getExactDencity (self, x = int, y = int, z = int, fromBackup = Any, cache_ref = Any): ...
	def getInterpolatedValue (self, pos = Any, fromBackup = Any): ...
	def getPolycount (self): ...
	def getVolume (self): ...
	def getSquare (self): ...
	def calcLocalScaceAABB (self): ...
	def calcWorldSpaceAABB (self): ...
	def tree (self): ...
	def vo (self): ...
	def cell (self, cx = int, cy = int, cz = int, create = Any, backup = Any): ...
	def attributes (self, cx = int, cy = int, cz = int, create = Any, backup = Any): ...
	def dirty (self, cx = int, cy = int, cz = int): ...
	def setOpacity (self, Opacity = float): ...
	def relaxGpu (self, center = Any, Radius = float, degree = float): ...
	def relaxVoxels (self, count = int): ...
	def relaxSurface (self, degree = float, tangent = Any, keep_sharp_boolean_edges = Any): ...
	def inScene (self): ...
	def clear (self): ...
	def clearNoUndo (self): ...
	def assignShader (self, shaderName = str): ...
	def setBoolShaderProperty (self, property = str, value = Any): ...
	def setFloatShaderProperty (self, property = str, value = float): ...
	def setColorShaderProperty (self, property = str, value = Any): ...
	def closeHoles (self, maxSize = int): ...
class Scene:
	def current (self): ...
	def sculptRoot (self): ...
	def curvesRoot (self): ...
	def getLayer (self, name = str, addIfNotExists = Any): ...
	def invalidateLayer (self, LayerID = int): ...
	def setActiveLayer (self, LayerID = int): ...
	def removeLayer (self, LayerID = int): ...
	def layerVisible (self, LayerID = int): ...
	def setLayerVisibility (self, LayerID = int, Visible = Any): ...
	def setLayerColorOpacity (self, LayerID = int, Opacity = float): ...
	def PaintObjectsCount (self): ...
	def PaintMaterialCount (self): ...
	def PaintUVSetsCount (self): ...
	def RemovePaintObject (self, idx = int): ...
	def RemovePaintMaterial (self, idx = int): ...
	def RemoveUVSet (self, idx = int): ...
	def PaintObjectName (self, idx = int): ...
	def PaintMaterialName (self, idx = int): ...
	def PaintUVSetName (self, idx = int): ...
class Curve:
	def __init__(self): ...
	def __init__(self): ...
	def __init__(self, ob = Any): ...
	def __init__(self, el = Any): ...
	def pointsCount (self): ...
	def point (self, idx = int): ...
	def removePoints (self, index = int, count = int): ...
	def curve (self): ...
	def renderPointsCount (self): ...
	def renderPoint (self, idx = int): ...
	def updatePoints (self): ...
	def closed (self): ...
	def add (self, p = Any, normal = Any, Radius = float): ...
	def addSharp (self, p = Any, normal = Any, Radius = float): ...
	def addSmooth (self, p = Any, normal = Any, Radius = float): ...
	def add (self, p = Any, normal = Any, inTangent = Any, outTangent = Any, Radius = float): ...
	def add (self, p = Any, normal = Any, inOutTangent = Any, Radius = float): ...
	def tubeToMesh (self, mesh = Any, hemisphere = Any): ...
	def fill (self, mesh = Any, thickness = float, relax_count = float, details_level = float, extrusion = float): ...
class SphericalCollision:
	def __init__(self): ...
	def __init__(self, cellsize = float): ...
	def __init__(self): ...
	def setUnit (self, u = float): ...
	def clear (self): ...
	def addSphere (self, p = Any, radius = float): ...
	def collides (self, p = Any, radius = float): ...
	def sphere (self, idx = int): ...
class ui:
	def wait (self, id = str, max_seconds = float): ...
	def setSliderValue (self, id = str, value = float): ...
	def getSliderValue (self, id = str): ...
	def setEditBoxValue (self, id = str, value = str): ...
	def setEditBoxValue (self, id = str, value = int): ...
	def setEditBoxValue (self, id = str, value = float): ...
	def getEditBoxValue (self, id = str, result = Any): ...
	def getEditBoxValue (self, id = str): ...
	def apply (self): ...
	def setFileForFileDialog (self, filename = str): ...
	def getBoolField (self, id = str): ...
	def setBoolValue (self, id = str, value = Any): ...
	def currentRoom (self): ...
	def toRoom (self, name = str): ...
	def roomsCount (self): ...
	def roomName (self, index = int): ...
	def roomID (self, index = int): ...
	def toolParam (self, B = Any): ...
	def removeToolParam (self, B = Any): ...
	def getOption (self, id = str): ...
	def setOption (self, id = str, value = str): ...
	def setOption (self, id = str, value = Any): ...
	def setOption (self, id = str, value = float): ...
	def hideDontShowAgainMessage (self, id = str): ...
	def showInfoMessage (self, infoID = str, milliseconds = int): ...
class dialog:
	def __init__(self): ...
	def text (self, id = str): ...
	def caption (self, id = str): ...
	def width (self, w = int): ...
	def modal (self): ...
	def noModal (self): ...
	def buttons (self, list = str): ...
	def topRight (self): ...
	def ok (self): ...
	def cancel (self): ...
	def yes (self): ...
	def no (self): ...
	def warn (self): ...
	def question (self): ...
	def undoWorks (self): ...
	def transparentBackground (self): ...
	def fadeDialogsBackground (self): ...
	def dontShowAgainCheckbox (self): ...
	def params (self, params = Any): ...
	def show (self): ...
class io:
	def installPath (self): ...
	def dataPath (self): ...
	def documents (self, path = str): ...
	def fileExists (self, path = str): ...
	def toFullPathInDataFolder (self, path = str): ...
	def toFullPathInInstallFolder (self, path = str): ...
	def strFromFile (self, filename = str): ...
	def strToFile (self, text = str, filename = str): ...
	def cursorPos (self): ...
	def snappedCursorPos (self): ...
	def wholeScreen (self): ...
	def workArea (self): ...
	def progressBar (self, stage = float, max_stage = float, message = str): ...
	def progressBarInWindowHeader (self, stage = float, max_stage = float, message = str): ...
	def setWindowTitle (self, text = str, seconds = float): ...
	def step (self, count = int): ...
	def exec (self, command = str, arguments = str): ...
	def execAndWait (self, command = str, arguments = str): ...
	def ListFiles (self, folder = str, mask = str, recursive = Any): ...
	def ListFolders (self, startFolder = str): ...
	def supportedImagesFormats (self): ...
	def supportedMeshesFormats (self): ...
	def openFileDialog (self, extensions = str, fileName = Any): ...
	def openFileDialog (self, extensions = str): ...
	def openFilesDialog (self, extensions = str): ...
	def saveFileDialog (self, extensions = str, fileName = Any): ...
	def saveFileDialog (self, extensions = str): ...
	def currentSceneFilepath (self): ...
class logger:
	def __init__(self): ...
	def __init__(self, filename = str): ...
	def __init__(self): ...
	def open (self): ...
	def showMessage (self): ...
	def directTo (self, filename = str): ...
	def getFullPath (self): ...
	def flush (self): ...
	def newline (self): ...
	def timestamp (self): ...
	def startTimer (self): ...
	def endTimer (self): ...
	def floatPrecission (self, signs = int): ...
class prim:
	def __init__(self): ...
	def class_name (self): ...
	def name (self, s = str): ...
	def name (self): ...
	def add (self, v = Any): ...
	def subtract (self, v = Any): ...
	def intersect (self, v = Any): ...
	def merge (self, v = Any, op = Any): ...
	def mesh (self): ...
	def color (self, CL = Any): ...
	def color (self, r = float, g = float, b = float, a = float): ...
	def color (self, r = float, g = float, b = float): ...
	def color (self, colorid = str): ...
	def gloss (self, value = float): ...
	def roughness (self, value = float): ...
	def metal (self, value = float): ...
	def opacity (self, value = float): ...
	def details (self, det_level = Any): ...
	def details (self): ...
	def transform (self, t = Any): ...
	def transform (self): ...
	def scale (self, scale = float): ...
	def scale (self, v = Any): ...
	def scale (self): ...
	def translate (self, _pos = Any): ...
	def translate (self): ...
	def translate (self, x = float, y = float, z = float): ...
	def x (self, x = float): ...
	def y (self, y = float): ...
	def z (self, z = float): ...
	def auto_divide (self, average_div = float): ...
	def step_divide (self, step = float): ...
	def fillet (self, radius = float): ...
	def debug_on (self, isOn = Any): ...
	def debug_clear (self): ...
	def push_transform (self, t = Any): ...
	def push_translate (self, d = Any): ...
	def push_scale (self, scale = float): ...
	def push_scale (self, s = Any): ...
	def push_details (self, details_modulator = float): ...
	def reset_transform (self): ...
	def fillet_relative (self): ...
class box:
	def __init__(self): ...
	def __init__(self, sizeX = float, sizeY = float, sizeZ = float): ...
	def __init__(self, size = Any): ...
	def __init__(self, pos = Any, size = Any): ...
	def __init__(self, pos = Any, size = Any, fillet = float): ...
	def axis (self, directionX = Any): ...
	def axis (self, directionX = Any, directionY = Any): ...
	def axis (self, directionX = Any, directionY = Any, directionZ = Any): ...
	def reset_axis (self): ...
	def axis_x (self): ...
	def axis_y (self): ...
	def axis_z (self): ...
	def divide (self, nx = int, ny = int, nz = int): ...
	def size (self, _size = Any): ...
	def size (self, x = float, y = float, z = float): ...
	def size (self): ...
	def fillet_relative (self): ...
class torus:
	def __init__(self): ...
	def __init__(self, ringRadius = Any, crossSectionRadius = Any): ...
	def __init__(self, pos = Any, ringRadius = Any, crossSectionRadius = Any): ...
	def slices (self, _slices = Any): ...
	def slices (self): ...
	def rings (self, _rings = Any): ...
	def rings (self): ...
	def radius (self, r = Any): ...
	def radius (self): ...
	def section_radius (self, section_r = Any): ...
	def section_radius (self): ...
	def diameter (self, d = Any): ...
	def diameter (self): ...
	def section_diameter (self, section_d = Any): ...
	def section_diameter (self): ...
	def sector_on (self, _switch = Any): ...
	def sector_on (self): ...
	def slices_angle (self, angle = Any): ...
	def slices_angle (self): ...
	def rings_angle (self, angle = Any): ...
	def rings_angle (self): ...
class sphere:
	def __init__(self): ...
	def __init__(self, radius = float): ...
	def __init__(self, pos = Any, radius = float): ...
	def radius (self, r = Any): ...
	def radius (self): ...
	def diameter (self, d = Any): ...
	def diameter (self): ...
	def sub_division (self, subdiv = Any): ...
	def sub_division (self): ...
	def sub_div_mode (self, divmode = Any): ...
	def sub_div_mode (self): ...
	def rings (self, _rings = Any): ...
	def rings (self): ...
	def slices (self, _slices = Any): ...
	def slices (self): ...
	def sector_on (self, _switch = Any): ...
	def sector_on (self): ...
	def slice_from (self, angle = Any): ...
	def slice_from (self): ...
	def slice_to (self, angle = Any): ...
	def slice_to (self): ...
	def ring_from (self, angle = Any): ...
	def ring_from (self): ...
	def ring_to (self, angle = Any): ...
	def ring_to (self): ...
class ellipse:
	def __init__(self): ...
	def __init__(self, pos = Any, rx = float, ry = float, rz = float): ...
	def __init__(self, pos = Any, size = Any): ...
	def __init__(self, size = Any): ...
	def axis (self, directionX = Any, directionY = Any, directionZ = Any): ...
	def reset_axis (self): ...
	def size (self, _size = Any): ...
	def size (self): ...
class cylinder:
	def __init__(self): ...
	def __init__(self, height = Any, radiusTop = Any, radiusBottom = Any, fillet = Any): ...
	def __init__(self, posTop = Any, posBottom = Any, radiusTop = Any, radiusBottom = Any, fillet = Any): ...
	def positionTop (self, pos = Any): ...
	def positionTop (self): ...
	def positionBottom (self, pos = Any): ...
	def positionBottom (self): ...
	def radiusTop (self, r = Any): ...
	def radiusTop (self): ...
	def radiusBottom (self, r = Any): ...
	def radiusBottom (self): ...
	def radius (self, r = Any): ...
	def radius (self): ...
	def diameterTop (self, d = Any): ...
	def diameterTop (self): ...
	def diameterBottom (self, r = Any): ...
	def diameterBottom (self): ...
	def diameter (self, d = Any): ...
	def diameter (self): ...
	def height (self, _height = Any): ...
	def height (self): ...
	def sectorAngle (self, angle = Any): ...
	def sectorAngle (self): ...
	def topCapScale (self, scale = Any): ...
	def topCapScale (self): ...
	def bottomCapScale (self, scale = Any): ...
	def bottomCapScale (self): ...
	def slices (self, nslices = Any): ...
	def slices (self): ...
	def rings (self, nrings = Any): ...
	def rings (self): ...
	def caps (self, ncaps = Any): ...
	def caps (self): ...
	def fillet_relative (self): ...
class cone:
	def __init__(self): ...
	def __init__(self, height = Any, radiusBottom = Any, fillet = Any): ...
	def __init__(self, posTop = Any, posBottom = Any, radiusBottom = Any, fillet = Any): ...
	def radius (self, r = Any): ...
	def radius (self): ...
	def diameter (self, d = Any): ...
	def diameter (self): ...
	def fillet_relative (self): ...
class tube:
	def __init__(self): ...
	def __init__(self, height = Any, radiusTop = Any, radiusBottom = Any): ...
	def __init__(self, height = Any, radiusTop = Any, radiusBottom = Any, fillet = Any): ...
	def __init__(self, height = Any, radiusTop = Any, radiusBottom = Any, relativeHoleRadius = Any, fillet = Any): ...
	def __init__(self, posTop = Any, posBottom = Any, radiusTop = Any, radiusBottom = Any, relativeHoleRadius = Any): ...
	def __init__(self, posTop = Any, posBottom = Any, radiusTop = Any, radiusBottom = Any, relativeHoleRadius = Any, fillet = Any): ...
	def relativeHoleRadius (self, r = Any): ...
	def relativeHoleRadius (self): ...
	def thickness (self, w = Any): ...
	def thickness (self): ...
	def fillet_relative (self): ...
class gear:
	def __init__(self): ...
	def __init__(self, height = Any, radiusTop = Any, radiusBottom = Any): ...
	def __init__(self, height = Any, radiusTop = Any, radiusBottom = Any, depth = float, sharpness = float, order = Any): ...
	def __init__(self, posTop = Any, posBottom = Any, radiusTop = Any, radiusBottom = Any, depth = float, sharpness = float, order = Any): ...
	def depth (self, __depth = Any): ...
	def depth (self): ...
	def sharpness (self, sharp = Any): ...
	def sharpness (self): ...
	def order (self, nteeth = Any): ...
	def order (self): ...
class ngon:
	def __init__(self): ...
	def __init__(self, height = Any, radiusTop = Any, radiusBottom = Any, order = Any): ...
	def __init__(self, height = Any, radiusTop = Any, radiusBottom = Any, fillet = Any, order = Any): ...
	def __init__(self, posTop = Any, posBottom = Any, radiusTop = Any, radiusBottom = Any, order = Any): ...
	def fillet_relative (self): ...
class capsule:
	def __init__(self): ...
	def __init__(self, height = Any, radiusTop = Any, radiusBottom = Any): ...
	def __init__(self, posTop = Any, posBottom = Any, radiusTop = Any, radiusBottom = Any): ...
class SpiralProfile(Enum):
	CIRCLE = ...
	RECTANGLE = ...
class spiral:
	def __init__(self): ...
	def __init__(self, out_radius = Any, in_radius = Any, _sstep = Any, nturns = Any): ...
	def radius (self, r = Any): ...
	def radius (self): ...
	def profile_radius (self, r = Any): ...
	def profile_radius (self): ...
	def diameter (self, d = Any): ...
	def diameter (self): ...
	def profile_diameter (self, d = Any): ...
	def profile_diameter (self): ...
	def turns (self, nturns = Any): ...
	def turns (self): ...
	def step (self, vstep = Any): ...
	def step (self): ...
	def profile_type (self, type = Any): ...
	def profile_rect (self, width = Any, height = Any): ...
	def clock_wise (self, clockWise = Any): ...
	def clock_wise (self): ...
	def profile_height (self): ...
	def profile_width (self): ...
	def slices (self, nslices = Any): ...
	def slices (self): ...
	def rings (self, nrings = Any): ...
	def rings (self): ...
	def caps (self, ncaps = Any): ...
	def caps (self): ...
class FontStyle(Enum):
	Regular = ...
	Italic = ...
	Underline = ...
	StrikeThrough = ...
class FontWeight(Enum):
	Dont = ...
	Thin = ...
	ExtraLight = ...
	Light = ...
	Normal = ...
	Medium = ...
	DemiBold = ...
	Bold = ...
	ExtraBold = ...
	Black = ...
class FontInfo:
	size: Any
	weight: Any
	style: Any
	fname: Any
class Font:
	def __init__(self): ...
	def __init__(self, _finfo = Any): ...
	def __init__(self, _fname = Any): ...
	def __init__(self, _fname = Any, _st = Any): ...
	def size (self, _size = Any): ...
	def size (self): ...
	def weight (self, weight = Any): ...
	def weight (self): ...
	def style (self, st = Any): ...
	def style (self): ...
	def name (self, _fname = Any): ...
	def name (self): ...
	def select (self): ...
class text:
	def __init__(self): ...
	def __init__(self, s = str): ...
	def __init__(self, s = Any): ...
	def string (self, s = Any): ...
	def string (self): ...
	def font (self, f = Any): ...
	def font (self): ...
	def width (self, w = Any): ...
	def width (self): ...
	def depth (self, d = Any): ...
	def depth (self): ...
	def bendRadius (self, radius = Any): ...
	def bendRadius (self): ...
	def extraRotation (self, rotation = Any): ...
	def extraRotation (self): ...
	def invertBending (self, _binvert = Any): ...
	def invertBending (self): ...
class lathe:
	def __init__(self): ...
	def __init__(self): ...
	def type (self, t = Any): ...
	def type (self): ...
	def add_point (self, point = Any, st = int): ...
	def profile (self): ...
	def reset (self): ...
	def clear (self): ...
class image:
	def __init__(self): ...
	def topTexture (self, _texture = str): ...
	def topTexture (self): ...
	def topBumpTexture (self, _texture = str): ...
	def topBumpTexture (self): ...
	def bottomTexture (self, _texture = str): ...
	def bottomTexture (self): ...
	def bottomBumpTexture (self, _texture = str): ...
	def bottomBumpTexture (self): ...
	def strencilTexture (self, _texture = str): ...
	def strencilTexture (self): ...
	def bottomStrencilTexture (self, _texture = str): ...
	def bottomStrencilTexture (self): ...
	def basicThickness (self, _thickness = Any): ...
	def basicThickness (self): ...
	def bumpThickness (self, _thickness = Any): ...
	def bumpThickness (self): ...
	def taperAngle (self, _angle = Any): ...
	def taperAngle (self): ...
	def topBottomWeight (self, weight = Any): ...
	def topBottomWeight (self): ...
	def sizeInScene (self, _size = Any): ...
	def sizeInScene (self): ...
class ThreadProfile(Enum):
	ThreadNone = ...
	ThreadTriangle = ...
	ThreadTrapeze = ...
	ThreadRectangular = ...
	ThreadRound = ...
	ThreadPersistent = ...
class thread:
	def __init__(self): ...
	def diameter (self, d = Any): ...
	def diameter (self): ...
	def pitch (self, p = Any): ...
	def pitch (self): ...
	def stub (self, l = Any): ...
	def stub (self): ...
	def height (self, h = Any): ...
	def height (self): ...
	def turns (self, n = Any): ...
	def turns (self): ...
	def clockwise (self, cw = Any): ...
	def clockwise (self): ...
	def close (self, b = Any): ...
	def close (self): ...
	def profile (self, prf = Any): ...
	def profile (self): ...
class ThreadStudBodyType(Enum):
	StudCylinder = ...
	StudCone = ...
class threadStud:
	def __init__(self): ...
	def diameter (self, d = Any): ...
	def diameter (self): ...
	def diameterTop (self, d = Any): ...
	def diameterTop (self): ...
	def diameterBottom (self, d = Any): ...
	def diameterBottom (self): ...
	def length (self, l = Any): ...
	def length (self): ...
	def threadLength (self): ...
	def enableThread (self, enable = Any): ...
	def enableThread (self): ...
	def bodyType (self, bt = Any): ...
	def bodyType (self): ...
class SlitType(Enum):
	none = ...
	Slot = ...
	Phillipse = ...
	Pozidriv = ...
	Robertson = ...
	HexSocket = ...
	SecurityHexSocket = ...
	Torx = ...
	SecurityTorx = ...
	TriWing = ...
	TorqSet = ...
	TripleSquare = ...
	Polydrive = ...
	DoubleSquare = ...
	SplineDrive = ...
	DoubleHex = ...
	Bristol = ...
	Pentalobular = ...
	Frearson = ...
	SnakeEyes = ...
	TA = ...
	TP3 = ...
	MorTorq = ...
	ClutCHG = ...
	ClutCHA = ...
	GroupEyes = ...
class Slit:
	def __init__(self): ...
	def __init__(self, w = float, h = float, d = float, t = Any): ...
	def type (self, _t = Any): ...
	def type (self): ...
	def width (self, _w = Any): ...
	def width (self): ...
	def height (self, _h = Any): ...
	def height (self): ...
	def depth (self, _d = Any): ...
	def depth (self): ...
class BoltHeadType(Enum):
	BoltNone = ...
	BoltHexa = ...
	Countersunk = ...
	BoltRound = ...
	Pan = ...
	Dome = ...
	Oval = ...
	Square = ...
	TShaped = ...
	Cylinder = ...
	Lamb = ...
	Rim = ...
	Eye = ...
	Bugle = ...
	Clop = ...
class HeadParams:
	def __init__(self): ...
	def __init__(self, _type = int, _param = Any): ...
	def __init__(self): ...
	def setData (self, _type = int, param = Any): ...
	def getData (self): ...
	def copy (self, h = Any): ...
	def release (self): ...
class HeadBaseParams:
	def __init__(self): ...
	def __init__(self, _d = float, _h = float): ...
	def diameter (self, _d = float): ...
	def height (self, _h = float): ...
	_diameter: Any
	_height: Any
class TShapedParams:
	def __init__(self): ...
	def __init__(self, _d = float, _h = float, _w = float): ...
	def diameter (self, _d = float): ...
	def height (self, _h = float): ...
	def width (self, _w = float): ...
	_diameter: Any
	_height: Any
	_width: Any
class LambParams:
	def __init__(self): ...
	def __init__(self, _l = float, _dtop = float, _dbottom = float, _hh = float, _h = float, _thick = float): ...
	def length (self, _l = float): ...
	def diameterTop (self, _d = float): ...
	def diameterBottom (self, _d = float): ...
	def height (self, _h = float): ...
	def headHeight (self, _h = float): ...
	def thickness (self, _t = float): ...
	_length: Any
	_diameterTop: Any
	_diameterBottom: Any
	_headHeight: Any
	_height: Any
	_thickness: Any
class RimParams:
	def __init__(self): ...
	def __init__(self, _d = float, _h = float, _d1 = float, _d2 = float): ...
	def shoulderDiameter (self, _d = float): ...
	def shoulderHeight (self, _h = float): ...
	def inRingDiameter (self, _d = float): ...
	def outRingDiameter (self, _d = float): ...
	_shoulderDiameter: Any
	_shoulderHeight: Any
	_inRingDiameter: Any
	_outRingDiameter: Any
class EyeParams:
	def __init__(self): ...
	def __init__(self, _thick = float, _d1 = float, _d2 = float): ...
	def inRingDiameter (self, _d = float): ...
	def outRingDiameter (self, _d = float): ...
	def thickness (self, _t = float): ...
	_thickness: Any
	_inRingDiameter: Any
	_outRingDiameter: Any
class boltHead:
	def __init__(self): ...
	def head (self, _h = Any): ...
	def head (self): ...
	def head (self): ...
	def head (self, _type = Any, data = Any): ...
	def slit (self, _s = Any): ...
	def slit (self): ...
	def slit (self): ...
class NutType(Enum):
	NutNone = ...
	NutHexa = ...
	Quard = ...
	Acorn = ...
	Lowacorn = ...
	NutFlange = ...
	Slits = ...
	Radial = ...
	NutLamb = ...
	NutRim = ...
	Selflock = ...
	NutTShaped = ...
	Clamplever = ...
	NtCount = ...
class NutHeadBaseParams:
	def __init__(self): ...
	def __init__(self, t = Any, d = float, h = float): ...
	def diameter (self, d = Any): ...
	def diameter (self): ...
	def height (self, h = Any): ...
	def height (self): ...
	def type (self, t = int): ...
	def type (self): ...
	def copy (self, p = Any): ...
class NutHexaParams:
	def __init__(self): ...
	def __init__(self, d = float, h = float): ...
class NutAcornParams:
	def __init__(self): ...
	def __init__(self, d = float, h = float, h1 = float): ...
	def facetHeight (self, _h = Any): ...
	def facetHeight (self): ...
	def copy (self, p = Any): ...
class NutLowAcornParams:
	def __init__(self): ...
	def __init__(self, d = float, h = float, h1 = float): ...
class NutSelfLockParams:
	def __init__(self): ...
	def __init__(self, d = float, h = float, h1 = float): ...
class NutTShapedParams:
	def __init__(self): ...
	def __init__(self, d = float, h = float, h1 = float): ...
class NutFlangeParams:
	def __init__(self): ...
	def __init__(self, d = float, h = float): ...
	def __init__(self, d = float, h = float, fw = float, fh = float): ...
	def facetWidth (self, w = Any): ...
	def facetHeight (self, h = Any): ...
	def facetWidth (self): ...
	def facetHeight (self): ...
	def copy (self, p = Any): ...
class NutRadialParams:
	def __init__(self): ...
	def __init__(self, d = float, h = float): ...
	def __init__(self, d = float, h = float, d1 = float, d2 = float): ...
	def holeDiameter (self, d = Any): ...
	def holeDepth (self, d = Any): ...
	def holeDiameter (self): ...
	def holeDepth (self): ...
	def holePlace (self, place = Any): ...
	def holePlace (self): ...
	def copy (self, p = Any): ...
class NutLambParams:
	def __init__(self): ...
	def __init__(self, d = float, h = float): ...
	def length (self, _l = Any): ...
	def diameterBottom (self, _d = Any): ...
	def diameterTop (self, _d = Any): ...
	def headHeight (self, _h = Any): ...
	def thickness (self, _t = Any): ...
	def length (self): ...
	def diameterBottom (self): ...
	def diameterTop (self): ...
	def headHeight (self): ...
	def thickness (self): ...
	def copy (self, p = Any): ...
class NutSlitsParams:
	def __init__(self): ...
	def __init__(self, d = float, h = float): ...
	def width (self, w = Any): ...
	def length (self, l = Any): ...
	def count (self, n = Any): ...
	def width (self): ...
	def length (self): ...
	def count (self): ...
	def copy (self, p = Any): ...
class NutRimParams:
	def __init__(self): ...
	def __init__(self, d = float, h = float): ...
	def inRingDiameter (self, _d = Any): ...
	def outRingDiameter (self, _d = Any): ...
	def inRingDiameter (self): ...
	def outRingDiameter (self): ...
	def copy (self, p = Any): ...
class NutClampLever:
	def __init__(self): ...
	def __init__(self, d = float, h = float): ...
	def holderDiameter (self, _d = Any): ...
	def length (self, _l = Any): ...
	def holderDiameter (self): ...
	def length (self): ...
	def copy (self, p = Any): ...
class nut:
	def __init__(self): ...
	def __init__(self): ...
	def setTypeData (self, data = Any): ...
	def getTypeData (self): ...
	def threadDiameter (self, d = Any): ...
	def threadDiameter (self): ...
	def pitch (self, p = Any): ...
	def pitch (self): ...
	def enableThread (self, f = Any): ...
	def enableThread (self): ...
	def threadType (self, _t = Any): ...
	def threadType (self): ...
class ThreadSurface(Enum):
	ThreadCylinder = ...
	ThreadCone = ...
	ThreadEdge = ...
class bolt:
	def __init__(self): ...
	def head (self, _h = Any): ...
	def head (self): ...
	def diameter (self, _d = Any): ...
	def diameter (self): ...
	def pitch (self, _p = Any): ...
	def pitch (self): ...
	def threadHeight (self, _h = Any): ...
	def threadHeight (self): ...
	def length (self, _l = Any): ...
	def length (self): ...
	def threadLength (self, _l = Any): ...
	def threadLength (self): ...
	def threadType (self, _t = Any): ...
	def threadType (self): ...
	def underhead (self, _uh = Any): ...
	def underhead (self): ...
	def uwidth (self, _uw = Any): ...
	def uwidth (self): ...
	def uheight (self, _uh = Any): ...
	def uheight (self): ...
	def nutType (self, _t = Any): ...
	def nutType (self): ...
	def nutLocation (self, _loc = Any): ...
	def nutLocation (self): ...
	def nutHeight (self, _h = Any): ...
	def nutHeight (self): ...
class screw:
	def __init__(self): ...
	def head (self, _h = Any): ...
	def head (self): ...
	def diameter (self, _d = Any): ...
	def diameter (self): ...
	def pitch (self, _p = Any): ...
	def pitch (self): ...
	def threadDiameter (self, _d = Any): ...
	def threadDiameter (self): ...
	def threadHeight (self, _h = Any): ...
	def threadHeight (self): ...
	def threadLength (self, _l = Any): ...
	def threadLength (self): ...
	def length (self, _l = Any): ...
	def length (self): ...
	def underhead (self, _uh = Any): ...
	def underhead (self): ...
	def uwidth (self, _uw = Any): ...
	def uwidth (self): ...
	def uheight (self, _uh = Any): ...
	def uheight (self): ...
class washer:
	def __init__(self): ...
	def innerDiameter (self, _d = Any): ...
	def innerDiameter (self): ...
	def outerDiameter (self, _d = Any): ...
	def outerDiameter (self): ...
	def conusDiameter (self, _d = Any): ...
	def conusDiameter (self): ...
	def thickness (self, _s = Any): ...
	def thickness (self): ...
	def height (self, _h = Any): ...
	def height (self): ...
	def facet (self, _f = Any): ...
	def facet (self): ...
	def type (self, _t = Any): ...
	def type (self): ...
class freeform:
	def __init__(self): ...
	def __init__(self, _ffname = str, _ffsubname = str): ...
	def __init__(self): ...
	def symx (self, x = Any): ...
	def symy (self, y = Any): ...
	def symz (self, z = Any): ...
	def size (self, x = float, y = float, z = float): ...
	def size (self, v = Any): ...
	def ffname (self, name = str): ...
	def ffname (self): ...
	def ffsubname (self, name = str): ...
	def ffsubname (self): ...
	def SetPoint (self, i = int, point = Any): ...
	def CountPoints (self): ...
	def ResetPoints (self): ...
	def ffSubNamesList (self): ...
	def ffSubNamesList (self, ffName = Any): ...
	def objsList (self): ...
	def ffControlPoints (self): ...
